### ISSUE TITLE
Pool Relays not updated

### ISSUE THREAD

**Issue by dgsqrs** [ADA-Ocean-Australia/adatools.io-support#5]
Hi there,
Using 'testnet', I had a pool relay. The registration has been made and the new relay is available in the current epoch.
It seems there is a problem on the Pools>Health screen, I only see the first relay.

Any idea ?

**Comment by CyberCyclone** [comment]
Can you please post your pool ID and I'll take a look.

**Comment by dgsqrs** [comment]
testnet -> c685a31a0eafd978577a7461eec717c60aa82dd3b4e6a1c430b200a7

**Comment by CyberCyclone** [comment]
They're both registered on the blockchain so it's just a case of ADAtools not crawling it yet. The server pings the relays to check if they're online, but since it's just a test server the crawl process takes longer.

It should update itself after a few hours.

Here's the result from a manual query:

```
{
  "data": {
    "stakePools": [
      {
        "relays": [
          {
            "ipv4": null,
            "dnsName": "relay2.testnet.hoth.ch"
          },
          {
            "ipv4": null,
            "dnsName": "relay1.testnet.hoth.ch"
          }
        ]
      }
    ]
  }
}
```

**Comment by dgsqrs** [comment]
Well the pool data are updated but not the relays.

**Comment by CyberCyclone** [comment]
I've just checked it and it looks like the listing has been updated.
